[tool.poetry]
name = "advent-of-code"
version = "0.1.0"
description = "Simple Env for aoc"
authors = ["ghirailghiro <ghirardellim1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
